"""Refactoring recommendations endpoint (roadmap Phase 10).

``GET /api/v1/refactor`` derives prioritized refactoring recommendations from
the live architecture risks. ``explain=true`` adds a short narrative plan
generated by the local LLM (best-effort — omitted if the model is unreachable).
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query, Request

from refactoring import RefactoringRecommender, recommend_narrative

from .audit import record_audit
from .deps import get_graph_client, get_llm

router = APIRouter()


@router.get("/refactor")
def refactor(
    request: Request,
    explain: bool = Query(default=False),
    limit: int = Query(default=100, ge=1, le=500),
    graph=Depends(get_graph_client),
):
    record_audit("refactor", detail={"explain": explain}, request=request)
    try:
        recs = RefactoringRecommender(graph).recommend(limit=limit)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(503, f"graph backend unavailable: {e}")

    narrative = recommend_narrative(recs, get_llm()) if explain else None
    return {"recommendations": recs, "total": len(recs), "narrative": narrative}
